source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'pg'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'jbuilder', '~> 2.2'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem 'bcrypt', require: 'bcrypt'

group :test do
  gem 'factory_girl_rails', :require => false
  gem 'faker'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'rspec-rails'
end

gem 'newrelic_rpm'
